# Generated by Django 2.2 on 2020-12-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0004_auto_20201222_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='allStar',
            field=models.BooleanField(),
        ),
    ]
