# Generated by Django 2.2 on 2020-12-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0005_auto_20201222_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerleague',
            name='league',
        ),
        migrations.RemoveField(
            model_name='playerleague',
            name='player',
        ),
        migrations.RemoveField(
            model_name='player',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='player',
            name='collegeName',
        ),
        migrations.RemoveField(
            model_name='player',
            name='country',
        ),
        migrations.RemoveField(
            model_name='player',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='player',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='player',
            name='heightInMeters',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='player',
            name='playerId',
        ),
        migrations.RemoveField(
            model_name='player',
            name='startNba',
        ),
        migrations.RemoveField(
            model_name='player',
            name='weightInKilograms',
        ),
        migrations.RemoveField(
            model_name='player',
            name='yearsPro',
        ),
        migrations.RemoveField(
            model_name='team',
            name='allStar',
        ),
        migrations.RemoveField(
            model_name='team',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='nbaFranchise',
        ),
        migrations.RemoveField(
            model_name='team',
            name='shortName',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teamID',
        ),
        migrations.AddField(
            model_name='player',
            name='balldontlie_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='full_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='height_feet',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='height_inches',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='nba_api_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight_pounds',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='balldontlie_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='full_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='nba_api_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='year_founded',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='team',
            name='conference',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='nickname',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Conference',
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='PlayerLeague',
        ),
    ]
