# Generated by Django 2.2 on 2020-12-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0006_auto_20201224_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
    ]
