# Generated by Django 2.2 on 2020-12-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0007_remove_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='balldontlie_id',
            field=models.IntegerField(null=True),
        ),
    ]
