# Generated by Django 2.2 on 2020-12-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0008_auto_20201225_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='balldontlie_id',
            field=models.IntegerField(null=True),
        ),
    ]
