# Generated by Django 2.2 on 2020-12-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0010_auto_20201225_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaysFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_nba_api_id', models.IntegerField(unique=True)),
                ('team_nba_api_id', models.IntegerField()),
            ],
        ),
    ]
