# Generated by Django 2.2 on 2020-12-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0012_auto_20201225_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_from',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_to',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
