# Generated by Django 2.2 on 2020-12-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0013_auto_20201225_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='draft_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='draft_round',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='draft_year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
