# Generated by Django 2.2 on 2020-12-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0016_auto_20201225_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
