# Generated by Django 2.2 on 2020-12-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0017_auto_20201225_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
