# Generated by Django 2.2 on 2020-12-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0018_auto_20201225_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_from',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_to',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
