# Generated by Django 2.2 on 2020-12-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0019_auto_20201225_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nba_api_season_id', models.IntegerField()),
                ('nba_api_player_id', models.IntegerField()),
                ('nba_api_game_id', models.IntegerField()),
                ('game_date', models.DateField()),
                ('matchup', models.CharField(max_length=20, null=True)),
                ('is_win', models.BooleanField(null=True)),
                ('minutes', models.CharField(max_length=5, null=True)),
                ('fgm', models.IntegerField(null=True)),
                ('fga', models.IntegerField(null=True)),
                ('fg_pct', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('fg3m', models.IntegerField(null=True)),
                ('fg3a', models.IntegerField(null=True)),
                ('fg3_pct', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('ftm', models.IntegerField(null=True)),
                ('fta', models.IntegerField(null=True)),
                ('ft_pct', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('oreb', models.IntegerField(null=True)),
                ('dreb', models.IntegerField(null=True)),
                ('reb', models.IntegerField(null=True)),
                ('ast', models.IntegerField(null=True)),
                ('stl', models.IntegerField(null=True)),
                ('blk', models.IntegerField(null=True)),
                ('tov', models.IntegerField(null=True)),
                ('pf', models.IntegerField(null=True)),
                ('pts', models.IntegerField(null=True)),
                ('plus_minus', models.IntegerField(null=True)),
                ('video_available', models.BooleanField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='teamgame',
            old_name='ast',
            new_name='AST',
        ),
        migrations.RenameField(
            model_name='teamgame',
            old_name='blk',
            new_name='BLK',
        ),
        migrations.RenameField(
            model_name='teamgame',
            old_name='dreb',
            new_name='DREB',
        ),
        migrations.RenameField(
            model_name='teamgame',
            old_name='fg3a',
            new_name='FG3A',
        ),
        migrations.RenameField(
            model_name='teamgame',
            old_name='fg3m',
            new_name='FG3M',
        ),
        migrations.RenameField(
            model_name='teamgame',
            old_name='fg3_pct',
            new_name='FG3_PCT',
        ),
        migrations.RenameField(
            model_name='teamgame',
            old_name='fga',
            new_name='FGA',
        ),
        migrations.RenameField(
            model_name='teamgame',
            old_name='fgm',
            new_name='FGM',
        ),
        migrations.RenameField(
            model_name='teamgame',
            old_name='ft_pct',
            new_name='FG_PUT',
        ),
        migrations.RenameField(
            model_name='teamgame',
            old_name='fta',
            new_name='FTA',
        ),
        migrations.RenameField(
            model_name='teamgame',
            old_name='ftm',
            new_name='FTM',
        ),
        migrations.RenameField(
            model_name='teamgame',
            old_name='fg_pct',
            new_name='FT_PCT',
        ),
        migrations.RenameField(
            model_name='teamgame',
            old_name='minutes',
            new_name='MIN',
        ),
        migrations.RenameField(
            model_name='teamgame',
            old_name='oreb',
            new_name='OREB',
        ),
        migrations.RenameField(
            model_name='teamgame',
            old_name='pf',
            new_name='PF',
        ),
        migrations.RenameField(
            model_name='teamgame',
            old_name='pts',
            new_name='PTS',
        ),
        migrations.RenameField(
            model_name='teamgame',
            old_name='reb',
            new_name='REB',
        ),
        migrations.RenameField(
            model_name='teamgame',
            old_name='stl',
            new_name='STL',
        ),
        migrations.RenameField(
            model_name='teamgame',
            old_name='tov',
            new_name='TOV',
        ),
    ]
