# Generated by Django 2.2 on 2020-12-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0020_auto_20201226_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamgame',
            old_name='FG_PUT',
            new_name='FG_PCT',
        ),
    ]
