# Generated by Django 2.2 on 2020-12-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0021_auto_20201226_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgame',
            name='nba_api_game_id',
            field=models.IntegerField(),
        ),
    ]
