# Generated by Django 2.2 on 2020-12-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0023_auto_20201227_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergame',
            name='VIDEO_AVAILABLE',
            field=models.IntegerField(null=True),
        ),
    ]
